tokiwa-software/fuzion-idioms

src/idiom41ex.fz
src/idiom41ex2.fz

this makes it possible to make codepoint_array private

idiom41: replace codepoint_array by as_codepoints.as_array

---

src/idiom206ex.fz.expected_err
src/idiom32ex2.fz.expected_err
src/idiom60ex.fz.expected_err

An extra space is no longer printed and a line number in a stack trace changed.

idioms: update expected output

---

src/idiom206ex.fz.expected_err
src/idiom4ex2.fz.expected_err
src/idiom60ex.fz.expected_err

update expected err output

---

html/idiom287.html
src/idiom287.fuzion
src/idiom287ex.fz
src/idiom287ex.fz.expected_out

[Idiom 287](https://www.programming-idioms.org/idiom/287/number-of-bytes-of-a-string)

add idiom 287 Number of bytes of a string

---

html/idiom259.html
src/idiom259.fuzion
src/idiom259ex.fz
src/idiom259ex.fz.expected_out
src/idiom259ex2.fz
src/idiom259ex2.fz.expected_out

Idiom 259: [Split on several separators](https://www.programming-idioms.org/idiom/259/split-on-several-separators)

add idiom 259 Split on several separators

---

html/idiom283.html
src/idiom283.fuzion
src/idiom283ex.fz
src/idiom283ex.fz.expected_out

[Idiom 283](https://www.programming-idioms.org/idiom/283/split-with-a-custom-string-separator)

add idiom 283 Split with a custom string separator

---

html/idiom270.html
src/idiom270.fuzion
src/idiom270ex.fz
src/idiom270ex.fz.expected_out

Idiom 270 [Test for quiet or signaling NaN](https://www.programming-idioms.org/idiom/270/test-for-quiet-or-signaling-nan)

add idiom 270 Test for quiet or signaling NaN

---

src/idiom196.fuzion
src/idiom196ex.fz

changed in tokiwa-software/fuzion#4730

idiom196: reflect specification of effect type

---

src/idiom129ex.fz
src/idiom130ex.fz
src/idiom179ex.fz
src/idiom17ex.fz
src/idiom186ex2.fz
src/idiom198ex2.fz
src/idiom219ex.fz
src/idiom245ex.fz
src/idiom268ex.fz
src/idiom28ex.fz
src/idiom40ex.fz
src/idiom94ex.fz

made mandatory in tokiwa-software/fuzion#4915

add missing visibilities to redefinitions

---

src/idiom129ex.fz
src/idiom130ex.fz
src/idiom94ex.fz

requires tokiwa-software/fuzion#4956

fix errors caused by changes in fuzion language

---

src/idiom20ex.fz
src/idiom288ex.fz
src/idiom43ex.fz

see tokiwa-software/fuzion#5075

don't use double slash for comments

---

src/idiom330ex.fz

Fixed spelling mistake

---

html/idiom213.html
src/idiom213.fuzion
src/idiom213ex.fz
src/idiom213ex.fz.expected_out

add idiom 213 Case-insensitive string compare

---

html/idiom212.html
src/idiom212.fuzion
src/idiom212ex.fz

add idiom 212 Check if folder exists

---

html/idiom197.html
src/idiom197.fuzion
src/idiom197ex.fz

add idiom 197 Get a list of lines from a file

---

html/idiom56.html
src/idiom56.fuzion
src/idiom56ex.fz
src/idiom56ex.fz.skip

add idiom 56 Launch 1000 parallel tasks and wait for completion

---

html/idiom343.html
src/idiom343.fuzion
src/idiom343ex.fz
src/idiom343ex.fz.expected_out

add idiom 343 Rename file

---

html/idiom297.html
src/idiom297.fuzion
src/idiom297ex.fz
src/idiom297ex.fz.expected_out

add idiom 297 Sort a list of strings, case-insensitively

---

html/idiom172.html
html/idiom173.html

fix wrong example file reference

---

html/idiom329.html
src/idiom329.fuzion
src/idiom329ex.fz
src/idiom329ex.fz.expected_out

add idiom 329: Read value in a map
